/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_smstorage_sharedmemory_ShmgetAccesser */

#ifndef _Included_org_apache_spark_smstorage_sharedmemory_ShmgetAccesser
#define _Included_org_apache_spark_smstorage_sharedmemory_ShmgetAccesser
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_spark_smstorage_sharedmemory_ShmgetAccesser_GB
#define org_apache_spark_smstorage_sharedmemory_ShmgetAccesser_GB 1073741824L
#undef org_apache_spark_smstorage_sharedmemory_ShmgetAccesser_MAX_CACHE_COUNT
#define org_apache_spark_smstorage_sharedmemory_ShmgetAccesser_MAX_CACHE_COUNT 1024L
/*
 * Class:     org_apache_spark_smstorage_sharedmemory_ShmgetAccesser
 * Method:    init
 * Signature: (Ljava/lang/String;IJ)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_smstorage_sharedmemory_ShmgetAccesser_init
  (JNIEnv *, jobject, jstring, jint, jlong);

/*
 * Class:     org_apache_spark_smstorage_sharedmemory_ShmgetAccesser
 * Method:    libshmat
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_smstorage_sharedmemory_ShmgetAccesser_libshmat
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_apache_spark_smstorage_sharedmemory_ShmgetAccesser
 * Method:    libshmdt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_smstorage_sharedmemory_ShmgetAccesser_libshmdt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_apache_spark_smstorage_sharedmemory_ShmgetAccesser
 * Method:    writeData
 * Signature: (I[BI)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_smstorage_sharedmemory_ShmgetAccesser_writeData
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     org_apache_spark_smstorage_sharedmemory_ShmgetAccesser
 * Method:    readData
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_smstorage_sharedmemory_ShmgetAccesser_readData
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_apache_spark_smstorage_sharedmemory_ShmgetAccesser
 * Method:    release
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_smstorage_sharedmemory_ShmgetAccesser_release
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
